#!/bin/sh
#MISE description="Use secretlint to scan all staged files for secrets"
# shellcheck disable=SC2154

# Move to the original working directory so that `git diff` works
cd "$MISE_ORIGINAL_CWD" || exit 1

# Use the bundled config, or override with the path given as the first argument
config="${1:-$MISE_TASK_DIR/.secretlintrc.json}"

# Get diff of all staged files and exit if empty
git diff --cached --name-only --diff-filter=ACMR |
grep -q . || exit 0

# Run secretlint with the config
git diff --cached --name-only -z --diff-filter=ACMR |
xargs -0 secretlint --secretlintrc "$config" --no-glob
