[settings]
minimum_release_age = "7d"

[settings.task]
run_auto_install = false

[tools]
awscli = "latest"
go = "latest"
node = "24"
uv = "latest"

[task_config]
includes = [
  "git::https://github.com/nekrassov01/dotfiles.git//tasks?ref=main",
]
